version: '3'
services:
    laravel.test:
        build:
            context: .
            dockerfile: ./infra/php/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                WWWUSER: '${WWWUSER}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - 'php-fpm-socket:/var/run/php-fpm/'
        networks:
            - sail
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_started
    nginx:
        build:
            context: ./infra/nginx
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        environment:
            WWWUSER: '${WWWUSER}'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - './public:/usr/share/nginx/html/:ro'
            - 'php-fpm-socket:/var/run/php-fpm/'
        depends_on:
            - laravel.test
        networks:
            - sail
    postgres:
        image: postgres:14
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - sail-psql:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks:
            - sail
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -p 5432"]
            interval: 5s
            timeout: 5s
            retries: 3
    redis:
        image: 'redis:7.0.11-alpine3.18'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-psql:
        driver: local
    sail-redis:
        driver: local
    php-fpm-socket:
        driver: local
